[package]
name = "nes"
version = "1.0.0"
authors = ["PitchBlackNights <pitchblacknights@proton.me>"]
edition = "2024"

[dependencies]
log = "0.4"
once_cell = "1.21"
bitflags = "2.9"
md5 = "0.8"

[lints.clippy]
uninlined-format-args = "allow"
new-without-default = "allow"
